server:
    port: 8080
    servlet:
        context-path: /
        multipart:
            enabled: true
            max-file-size: 2MB
            max-request-size: 2MB

spring:
    cloud:
        compatibility-verifier:
            enabled: false

    mail:
        host: smtp.gmail.com
        port: 587
        username: vietvuongf@gmail.com
        password: iawfuweyatnsdbnh
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    #            required: true

    datasource:
#        url: "jdbc:mysql://192.168.1.113:3307/DoctorConnect"
        url: "jdbc:mysql://localhost:3307/DoctorConnect"
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 180129695892-g5shabf1spmrao596p3g7c4t1e58pdge.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://localhost:8080/login/oauth2/code/google
                        scope: openid, profile, email
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

momo:
    partner-code: MOMOLRJZ20181206
    return-url: http://localhost:5175/my-appointments
    end-point: https://test-payment.momo.vn/v2/gateway/api
    ipn-url: https://4b1a-2402-9d80-40b-e9e1-1de3-462d-24ab-fc67.ngrok-free.app/api/momo/ipn-handler
    access-key: mTCKt9W3eU1m39TW
    secret-key: SetA5RDnLHvt51AULf51DyauxUo3kDU6
    request-type: captureWallet

jwt:
    signerKey: "jJfGRQiKOkXdATzFxwdnDbwq4tyCZFgikucK9JTXAMqxZZQWvupKkBggAgdx2Mwa"
